language: java

jdk:
  - openjdk8

env:
  global:
    # WCRS_OSPLACES_KEY
    - secure: "dMlpKaW5J9WU9aQ7LrpaAl+gfVk3Ie8Yz6t4I93zVjJ9w2RyPOpuK9Nzvj8Lw6gQaA4pmM1Lda5yC06uD0+desOIS+tv6+3Zb/HOvlbXKe6DzvAOM505ODU2hS89oce1/d3TRi7UAwy1TLdDm9P2IjHMWHdOWE1yzsQCrF/3rKc="
    - WCRS_OSPLACES_URL="https://api.ordnancesurvey.co.uk/places/v1/addresses"

script: ./mvnw -B -Dmaven.test.skip=true -T 1C clean package
