# http://www.dropwizard.io/1.3.1/docs/manual/configuration.html#man-configuration
server:
  applicationConnectors:
    - type: http
      port: 9190
  adminConnectors:
    - type: http
      port: 9191

logging:
  level: INFO
  appenders:
    - type: console
      timeZone: UTC
    - type: file
      currentLogFilename: ${WCRS_ADDR_LOOKUP_LOGFILE:-/srv/java/os-places-address-lookup/logs/run.log}
      archivedLogFilenamePattern: ${WCRS_ADDR_LOOKUP_LOGFILE_PATTERN:-/srv/java/os-places-address-lookup/logs/run-archive-%d.log.gz}
      archivedFileCount: 5
      timeZone: UTC

properties:
  key: ${WCRS_OSPLACES_KEY}
  url: "https://api.ordnancesurvey.co.uk/places/v1/addresses"
  delimiter: ","