# http://www.dropwizard.io/1.3.1/docs/manual/configuration.html#man-configuration
server:
  applicationConnectors:
    - type: http
      port: 8005
  adminConnectors:
    - type: http
      port: 8006

logging:
  level: INFO
  appenders:
    - type: console
      timeZone: UTC
    - type: file
      currentLogFilename: ${WCRS_ADDR_LOOKUP_LOGFILE:-/srv/java/os-places-address-lookup/logs/run.log}
      archivedLogFilenamePattern: ${WCRS_ADDR_LOOKUP_LOGFILE_PATTERN:-/srv/java/os-places-address-lookup/logs/run-archive-%d.log.gz}
      archivedFileCount: 5
      timeZone: UTC

properties:
  key: ${WCRS_OSPLACES_KEY}
  url: "https://api.ordnancesurvey.co.uk/places/v1/addresses"
  # If enabled the service will not call OS Places and instead read previously
  # recorded results from JSON files in resources
  mock: ${WCRS_MOCK_ENABLED:-false}
  # To try and more closely mock calling out to OS places you can have the
  # service pause during each call. The default is a best guess at trying to
  # and take into account reading from the json file whilst delaying enough
  # to mimic a normal call to the service (typically 200 to 250 ms)
  mockDelay: ${WCRS_MOCK_DELAY:-200}
